version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sigopt
    versions:
    - 5.7.0
    - 7.3.0
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
