version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: PEP8 Syntax - flake8
          command: |
            . venv/bin/activate
            flake8 autotune/ --config=.flake8
      - run:
          name: Type Check - mypy
          command: |
            . venv/bin/activate
            mypy autotune/benchmarks/ autotune/core/ autotune/datasets/ autotune/util/

workflows:
  main:
    jobs:
      - build-and-test
